# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/chat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/chat.proto\x12\x04\x63hat\"\x8c\x01\n\x04\x43hat\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x0e\x63hat_author_id\x18\x02 \x01(\x04\x12\x16\n\x0e\x63hat_member_id\x18\x03 \x01(\r\x12#\n\x0b\x63hat_author\x18\x04 \x01(\x0b\x32\x0e.chat.ChatUser\x12#\n\x0b\x63hat_member\x18\x05 \x01(\x0b\x32\x0e.chat.ChatUser\"9\n\x11\x43reateChatRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x04\x12\x11\n\tauthor_id\x18\x02 \x01(\x04\"|\n\x08\x43hatUser\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x17\n\x0fprofile_picture\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07surname\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x04\x12\r\n\x05\x65mail\x18\x08 \x01(\t\".\n\x12\x43reateChatResponse\x12\x18\n\x04\x63hat\x18\x01 \x01(\x0b\x32\n.chat.Chat\"0\n\x14GetUserChatsResponse\x12\x18\n\x04\x63hat\x18\x01 \x03(\x0b\x32\n.chat.Chat\"(\n\x13GetUserChatsRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x04\"/\n\x13GetUserChatResponse\x12\x18\n\x04\x63hat\x18\x01 \x01(\x0b\x32\n.chat.Chat\"3\n\x12GetUserChatRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\x04\"2\n\x11\x44\x65leteChatRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tauthor_id\x18\x02 \x01(\x04\"%\n\x12\x44\x65leteChatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x02\n\x0b\x43hatService\x12?\n\nCreateChat\x12\x17.chat.CreateChatRequest\x1a\x18.chat.CreateChatResponse\x12\x45\n\x0cGetUserChats\x12\x19.chat.GetUserChatsRequest\x1a\x1a.chat.GetUserChatsResponse\x12\x42\n\x0bGetUserChat\x12\x18.chat.GetUserChatRequest\x1a\x19.chat.GetUserChatResponse\x12?\n\nDeleteChat\x12\x17.chat.DeleteChatRequest\x1a\x18.chat.DeleteChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHAT']._serialized_start=28
  _globals['_CHAT']._serialized_end=168
  _globals['_CREATECHATREQUEST']._serialized_start=170
  _globals['_CREATECHATREQUEST']._serialized_end=227
  _globals['_CHATUSER']._serialized_start=229
  _globals['_CHATUSER']._serialized_end=353
  _globals['_CREATECHATRESPONSE']._serialized_start=355
  _globals['_CREATECHATRESPONSE']._serialized_end=401
  _globals['_GETUSERCHATSRESPONSE']._serialized_start=403
  _globals['_GETUSERCHATSRESPONSE']._serialized_end=451
  _globals['_GETUSERCHATSREQUEST']._serialized_start=453
  _globals['_GETUSERCHATSREQUEST']._serialized_end=493
  _globals['_GETUSERCHATRESPONSE']._serialized_start=495
  _globals['_GETUSERCHATRESPONSE']._serialized_end=542
  _globals['_GETUSERCHATREQUEST']._serialized_start=544
  _globals['_GETUSERCHATREQUEST']._serialized_end=595
  _globals['_DELETECHATREQUEST']._serialized_start=597
  _globals['_DELETECHATREQUEST']._serialized_end=647
  _globals['_DELETECHATRESPONSE']._serialized_start=649
  _globals['_DELETECHATRESPONSE']._serialized_end=686
  _globals['_CHATSERVICE']._serialized_start=689
  _globals['_CHATSERVICE']._serialized_end=971
# @@protoc_insertion_point(module_scope)
