# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import chat_pb2 as protos_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChat = channel.unary_unary(
                '/chat.ChatService/CreateChat',
                request_serializer=protos_dot_chat__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.CreateChatResponse.FromString,
                _registered_method=True)
        self.GetUserChats = channel.unary_unary(
                '/chat.ChatService/GetUserChats',
                request_serializer=protos_dot_chat__pb2.GetUserChatsRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.GetUserChatsResponse.FromString,
                _registered_method=True)
        self.GetUserChat = channel.unary_unary(
                '/chat.ChatService/GetUserChat',
                request_serializer=protos_dot_chat__pb2.GetUserChatRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.GetUserChatResponse.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/chat.ChatService/DeleteChat',
                request_serializer=protos_dot_chat__pb2.DeleteChatRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.DeleteChatResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=protos_dot_chat__pb2.CreateChatRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.CreateChatResponse.SerializeToString,
            ),
            'GetUserChats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChats,
                    request_deserializer=protos_dot_chat__pb2.GetUserChatsRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.GetUserChatsResponse.SerializeToString,
            ),
            'GetUserChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChat,
                    request_deserializer=protos_dot_chat__pb2.GetUserChatRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.GetUserChatResponse.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=protos_dot_chat__pb2.DeleteChatRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.DeleteChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/CreateChat',
            protos_dot_chat__pb2.CreateChatRequest.SerializeToString,
            protos_dot_chat__pb2.CreateChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetUserChats',
            protos_dot_chat__pb2.GetUserChatsRequest.SerializeToString,
            protos_dot_chat__pb2.GetUserChatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetUserChat',
            protos_dot_chat__pb2.GetUserChatRequest.SerializeToString,
            protos_dot_chat__pb2.GetUserChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/DeleteChat',
            protos_dot_chat__pb2.DeleteChatRequest.SerializeToString,
            protos_dot_chat__pb2.DeleteChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
