# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/history.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "protos/history.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14protos/history.proto\x12\x07history"\x7f\n\x0bHistoryUser\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x17\n\x0fprofile_picture\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07surname\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x04\x12\r\n\x05\x65mail\x18\x08 \x01(\t"r\n\x07History\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x15\n\rcontent_title\x18\x04 \x01(\t\x12"\n\x04user\x18\x05 \x01(\x0b\x32\x14.history.HistoryUser"O\n\x14\x43reateHistoryRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x15\n\rcontent_title\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\r":\n\x15\x43reateHistoryResponse\x12!\n\x07history\x18\x01 \x01(\x0b\x32\x10.history.History"%\n\x12GetHistorysRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r"9\n\x13GetHistorysResponse\x12"\n\x08historys\x18\x01 \x03(\x0b\x32\x10.history.History"\x1f\n\x11GetHistoryRequest\x12\n\n\x02id\x18\x01 \x01(\r"7\n\x12GetHistoryResponse\x12!\n\x07history\x18\x01 \x01(\x0b\x32\x10.history.History"3\n\x14\x44\x65leteHistoryRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r")\n\x15\x44\x65leteHistoryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xc1\x02\n\x0eHistoryService\x12N\n\rCreateHistory\x12\x1d.history.CreateHistoryRequest\x1a\x1e.history.CreateHistoryResponse\x12H\n\x0bGetHystorys\x12\x1b.history.GetHistorysRequest\x1a\x1c.history.GetHistorysResponse\x12\x45\n\nGetHistory\x12\x1a.history.GetHistoryRequest\x1a\x1b.history.GetHistoryResponse\x12N\n\rDeleteHistory\x12\x1d.history.DeleteHistoryRequest\x1a\x1e.history.DeleteHistoryResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.history_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HISTORYUSER"]._serialized_start = 33
    _globals["_HISTORYUSER"]._serialized_end = 160
    _globals["_HISTORY"]._serialized_start = 162
    _globals["_HISTORY"]._serialized_end = 276
    _globals["_CREATEHISTORYREQUEST"]._serialized_start = 278
    _globals["_CREATEHISTORYREQUEST"]._serialized_end = 357
    _globals["_CREATEHISTORYRESPONSE"]._serialized_start = 359
    _globals["_CREATEHISTORYRESPONSE"]._serialized_end = 417
    _globals["_GETHISTORYSREQUEST"]._serialized_start = 419
    _globals["_GETHISTORYSREQUEST"]._serialized_end = 456
    _globals["_GETHISTORYSRESPONSE"]._serialized_start = 458
    _globals["_GETHISTORYSRESPONSE"]._serialized_end = 515
    _globals["_GETHISTORYREQUEST"]._serialized_start = 517
    _globals["_GETHISTORYREQUEST"]._serialized_end = 548
    _globals["_GETHISTORYRESPONSE"]._serialized_start = 550
    _globals["_GETHISTORYRESPONSE"]._serialized_end = 605
    _globals["_DELETEHISTORYREQUEST"]._serialized_start = 607
    _globals["_DELETEHISTORYREQUEST"]._serialized_end = 658
    _globals["_DELETEHISTORYRESPONSE"]._serialized_start = 660
    _globals["_DELETEHISTORYRESPONSE"]._serialized_end = 701
    _globals["_HISTORYSERVICE"]._serialized_start = 704
    _globals["_HISTORYSERVICE"]._serialized_end = 1025
# @@protoc_insertion_point(module_scope)
