# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\x12\x04user\"x\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x17\n\x0fprofile_picture\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07surname\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x04\x12\r\n\x05\x65mail\x18\x08 \x01(\t\"T\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"F\n GetUserByUsernamePasswordRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"=\n!GetUserByUsernamePasswordResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x83\x01\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x17\n\x0fprofile_picture\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07surname\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x04\x12\r\n\x05\x65mail\x18\x08 \x01(\t\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"/\n\x13GetUserByIdResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User2\xb8\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12l\n\x19GetUserByUsernamePassword\x12&.user.GetUserByUsernamePasswordRequest\x1a\'.user.GetUserByUsernamePasswordResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12\x42\n\x0bGetUserByID\x12\x18.user.GetUserByIdRequest\x1a\x19.user.GetUserByIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=147
  _globals['_CREATEUSERREQUEST']._serialized_start=149
  _globals['_CREATEUSERREQUEST']._serialized_end=233
  _globals['_CREATEUSERRESPONSE']._serialized_start=235
  _globals['_CREATEUSERRESPONSE']._serialized_end=281
  _globals['_GETUSERBYUSERNAMEPASSWORDREQUEST']._serialized_start=283
  _globals['_GETUSERBYUSERNAMEPASSWORDREQUEST']._serialized_end=353
  _globals['_GETUSERBYUSERNAMEPASSWORDRESPONSE']._serialized_start=355
  _globals['_GETUSERBYUSERNAMEPASSWORDRESPONSE']._serialized_end=416
  _globals['_GETUSERRESPONSE']._serialized_start=419
  _globals['_GETUSERRESPONSE']._serialized_end=550
  _globals['_GETUSERREQUEST']._serialized_start=552
  _globals['_GETUSERREQUEST']._serialized_end=586
  _globals['_GETUSERBYIDREQUEST']._serialized_start=588
  _globals['_GETUSERBYIDREQUEST']._serialized_end=620
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=622
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=669
  _globals['_USERSERVICE']._serialized_start=672
  _globals['_USERSERVICE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
